"""Updating DB

Revision ID: 6862efaf5809
Revises: 007325b15bf0
Create Date: 2025-10-07 16:05:20.469230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6862efaf5809'
down_revision = '007325b15bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_conditions', schema=None) as batch_op:
        batch_op.alter_column('condition_name',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('book_genres', schema=None) as batch_op:
        batch_op.alter_column('genre_name',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('inventory_num',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('lang_of_book',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('lang_original',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('dimensions',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('publishing_house',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('age_of_reader',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('place_name',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.alter_column('shelve_name',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.alter_column('shelve_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('place_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('age_of_reader',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('publishing_house',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('dimensions',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('lang_original',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('lang_of_book',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('inventory_num',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('book_genres', schema=None) as batch_op:
        batch_op.alter_column('genre_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('book_conditions', schema=None) as batch_op:
        batch_op.alter_column('condition_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
