"""rename cover_photo_uuid to cover_photo_url

Revision ID: 723078301cdf
Revises: fb5581a0db4f
Create Date: 2026-02-03 23:03:31.623634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '723078301cdf'
down_revision = 'fb5581a0db4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('cover_photo_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo_uuid', mysql.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('cover_photo_url')

    # ### end Alembic commands ###
