"""Initial migration

Revision ID: 99a7ddefb4a3
Revises: 
Create Date: 2026-01-31 14:49:30.921300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a7ddefb4a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ru', sa.String(length=30), nullable=True),
    sa.Column('en', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_name')
    )
    op.create_table('book_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre_name')
    )
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'LIBRARIAN', 'READER', name='role'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=25), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('librarians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_hired', sa.Boolean(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('notify_before_days', sa.Integer(), nullable=True),
    sa.Column('notify_after_days', sa.Integer(), nullable=True),
    sa.Column('is_every_day', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('place_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'place_name')
    )
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelve_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'shelve_name')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('is_on_hand', sa.Boolean(), nullable=True),
    sa.Column('inventory_num', sa.String(length=50), nullable=False),
    sa.Column('title_ru', sa.Text(), nullable=True),
    sa.Column('title_original', sa.Text(), nullable=True),
    sa.Column('series', sa.Text(), nullable=True),
    sa.Column('lang_of_book', sa.String(length=50), nullable=True),
    sa.Column('lang_original', sa.String(length=50), nullable=True),
    sa.Column('author_ru', sa.String(length=20), nullable=True),
    sa.Column('author_in_original_lang', sa.String(length=20), nullable=True),
    sa.Column('writing_year', sa.Integer(), nullable=True),
    sa.Column('transfer_year', sa.Integer(), nullable=True),
    sa.Column('translators', sa.Text(), nullable=True),
    sa.Column('explanation_ru', sa.Text(), nullable=True),
    sa.Column('applications', sa.Text(), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('edition_num', sa.Integer(), nullable=True),
    sa.Column('publishing_house', sa.String(length=50), nullable=True),
    sa.Column('isbn1', sa.String(length=13), nullable=True),
    sa.Column('isbn2', sa.String(length=13), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('book_genre_id', sa.Integer(), nullable=True),
    sa.Column('cover_photo_uuid', sa.String(length=40), nullable=True),
    sa.Column('age_of_reader', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('shelve_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('pages_quantity', sa.Integer(), nullable=True),
    sa.CheckConstraint('pages_quantity > 0'),
    sa.CheckConstraint('quantity >= 0'),
    sa.CheckConstraint('transfer_year > 1000'),
    sa.ForeignKeyConstraint(['book_genre_id'], ['book_genres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['condition_id'], ['book_conditions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shelve_id'], ['shelves.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'inventory_num')
    )
    op.create_table('bible_place_in_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('bible_book_id', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('verse', sa.Integer(), nullable=True),
    sa.Column('pages', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bible_book_id'], ['bible_books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('topic_name', sa.String(length=15), nullable=False),
    sa.Column('pages', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('pages', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('on_hands_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=20), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint('issue_date <= return_date'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('on_hands_books')
    op.drop_table('keywords')
    op.drop_table('books_topics')
    op.drop_table('bible_place_in_book')
    op.drop_table('books')
    op.drop_table('shelves')
    op.drop_table('places')
    op.drop_table('notification_settings')
    op.drop_table('librarians')
    op.drop_table('directors')
    op.drop_table('notifications')
    op.drop_table('libraries')
    op.drop_table('users')
    op.drop_table('document_types')
    op.drop_table('book_genres')
    op.drop_table('book_conditions')
    op.drop_table('bible_books')
    # ### end Alembic commands ###
