"""Make location_id required in books

Revision ID: bd03fbf7086c
Revises: ec1819c2ee3a
Create Date: 2026-02-02 11:33:17.986752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd03fbf7086c'
down_revision = 'ec1819c2ee3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
