"""расширено количество символов поля topic_name

Revision ID: d1c6b56bcfc9
Revises: df78d1048930
Create Date: 2026-08-28 00:51:11.872377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1c6b56bcfc9'
down_revision = 'df78d1048930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_topics', schema=None) as batch_op:
        batch_op.alter_column('topic_name',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_topics', schema=None) as batch_op:
        batch_op.alter_column('topic_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
