"""Remove is_on_hand from books table

Revision ID: d4f8c5e9a2b1
Revises: 723078301cdf
Create Date: 2026-02-16 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4f8c5e9a2b1'
down_revision = '723078301cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('is_on_hand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_on_hand', sa.Boolean(), nullable=True, server_default=sa.text('false')))

    # ### end Alembic commands ###
