"""расширено количество символов для поля notifiactions.title

Revision ID: d611b5c4e31e
Revises: d1c6b56bcfc9
Create Date: 2026-08-28 14:07:19.227299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd611b5c4e31e'
down_revision = 'd1c6b56bcfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###
