"""Add cascade delete for place to books

Revision ID: ec1819c2ee3a
Revises: 99a7ddefb4a3
Create Date: 2026-02-02 11:31:39.163106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1819c2ee3a'
down_revision = '99a7ddefb4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('books_ibfk_5'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'places', ['location_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('books_ibfk_5'), 'places', ['location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
