"""Make shelve_id required and cascade delete

Revision ID: fb5581a0db4f
Revises: bd03fbf7086c
Create Date: 2026-02-02 12:37:21.026826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb5581a0db4f'
down_revision = 'bd03fbf7086c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_ibfk_6', type_='foreignkey')
        batch_op.alter_column('shelve_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'shelves', ['shelve_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('books_ibfk_6'), 'shelves', ['shelve_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('shelve_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
